# Generated by Django 5.1.1 on 2024-11-04 23:23

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_about_image_alter_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
