# Generated by Django 5.1.1 on 2024-11-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_feature_feature_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['order'], 'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='about',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
