# Generated by Django 5.1.1 on 2024-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_alter_about_options_about_order_alter_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
