# Generated by Django 5.1.1 on 2024-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_home_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='intro_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
